[2025-04-17T23:55:43.182+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fixed_parquet_loader.load_csv_to_postgres scheduled__2025-04-17T23:40:00+00:00 [queued]>
[2025-04-17T23:55:43.188+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fixed_parquet_loader.load_csv_to_postgres scheduled__2025-04-17T23:40:00+00:00 [queued]>
[2025-04-17T23:55:43.189+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-04-17T23:55:43.198+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2025-04-17 23:40:00+00:00
[2025-04-17T23:55:43.203+0000] {standard_task_runner.py:57} INFO - Started process 274 to run task
[2025-04-17T23:55:43.207+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fixed_parquet_loader', 'load_csv_to_postgres', 'scheduled__2025-04-17T23:40:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/parquet_to_postgres_dbt.py', '--cfg-path', '/tmp/tmpj1074axa']
[2025-04-17T23:55:43.209+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask load_csv_to_postgres
[2025-04-17T23:55:43.265+0000] {task_command.py:416} INFO - Running <TaskInstance: fixed_parquet_loader.load_csv_to_postgres scheduled__2025-04-17T23:40:00+00:00 [running]> on host 1f73474bb86b
[2025-04-17T23:55:43.339+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fixed_parquet_loader' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T23:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T23:40:00+00:00'
[2025-04-17T23:55:43.349+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parquet_to_postgres_dbt.py", line 45, in load_csv_to_postgres
    cur.execute("""
psycopg2.errors.UndefinedTable: relation "staging_table" does not exist
LINE 2: ...              CREATE TEMP TABLE temp_import (LIKE staging_ta...
                                                             ^

[2025-04-17T23:55:43.359+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fixed_parquet_loader, task_id=load_csv_to_postgres, execution_date=20250417T234000, start_date=20250417T235543, end_date=20250417T235543
[2025-04-17T23:55:43.369+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task load_csv_to_postgres (relation "staging_table" does not exist
LINE 2: ...              CREATE TEMP TABLE temp_import (LIKE staging_ta...
                                                             ^
; 274)
[2025-04-17T23:55:43.386+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-17T23:55:43.404+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
