[2025-04-18T00:32:57.482+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:32:57.496+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2025-04-18T00:32:57.510+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:32:57.513+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2025-04-18T00:32:57.516+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> from DB
[2025-04-18T00:32:57.663+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-04-18T00:32:57.663+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:32:57.672+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-04-18T00:32:57.673+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:32:57.673+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]>
[2025-04-18T00:32:57.676+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:32:57.676+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-04-18T00:32:57.678+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:32:57.681+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-04-18T00:32:57.681+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [queued]>
[2025-04-18T00:32:57.682+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-18T00:32:57.690+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2025-04-18 00:25:00+00:00
[2025-04-18T00:32:57.695+0000] {standard_task_runner.py:57} INFO - Started process 244 to run task
[2025-04-18T00:32:57.698+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'parquet_to_csv_to_postgres_loader', 'load_csv_to_postgres', 'scheduled__2025-04-18T00:25:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/parquet_to_postgres_dbt.py', '--cfg-path', '/tmp/tmpd5zsn7l9']
[2025-04-18T00:32:57.700+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask load_csv_to_postgres
[2025-04-18T00:32:57.701+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0xffffb126daf0>]
[2025-04-18T00:32:57.757+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:32:57.760+0000] {task_command.py:416} INFO - Running <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [running]> on host 606609f4e4b0
[2025-04-18T00:32:57.760+0000] {settings.py:351} DEBUG - Disposing DB connection pool (PID 244)
[2025-04-18T00:32:57.761+0000] {settings.py:210} DEBUG - Setting up DB connection pool (PID 244)
[2025-04-18T00:32:57.761+0000] {settings.py:283} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-04-18T00:32:57.762+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [running]> from DB
[2025-04-18T00:32:57.805+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:32:57.807+0000] {taskinstance.py:925} DEBUG - Clearing XCom data
[2025-04-18T00:32:57.813+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-04-18T00:32:57.835+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-04-18T00:32:57.848+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parquet_to_csv_to_postgres_loader' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T00:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-18T00:25:00+00:00'
[2025-04-18T00:32:57.849+0000] {__init__.py:116} DEBUG - Preparing lineage inlets and outlets
[2025-04-18T00:32:57.849+0000] {__init__.py:157} DEBUG - inlets: [], outlets: []
[2025-04-18T00:32:57.873+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parquet_to_postgres_dbt.py", line 59, in load_csv_to_postgres
    """, (row['id'], row['csv_data']))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'id'
[2025-04-18T00:32:57.877+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:25:00+00:00 [running]> from DB
[2025-04-18T00:32:57.886+0000] {taskinstance.py:2430} DEBUG - Task Duration set to 0.212769
[2025-04-18T00:32:57.887+0000] {taskinstance.py:1458} DEBUG - Clearing next_method and next_kwargs.
[2025-04-18T00:32:57.888+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parquet_to_csv_to_postgres_loader, task_id=load_csv_to_postgres, execution_date=20250418T002500, start_date=20250418T003257, end_date=20250418T003257
[2025-04-18T00:32:57.897+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2025-04-18T00:32:57.897+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 76 for task load_csv_to_postgres ('id'; 244)
[2025-04-18T00:32:57.919+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-18T00:32:57.938+0000] {dagrun.py:734} DEBUG - number of tis tasks for <DagRun parquet_to_csv_to_postgres_loader @ 2025-04-18 00:25:00+00:00: scheduled__2025-04-18T00:25:00+00:00, state:running, queued_at: 2025-04-18 00:32:53.152021+00:00. externally triggered: False>: 0 task(s)
[2025-04-18T00:32:57.938+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
