[2025-04-18T00:32:50.733+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:32:50.794+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2025-04-18T00:32:50.808+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:32:50.811+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2025-04-18T00:32:50.815+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> from DB
[2025-04-18T00:32:51.030+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-04-18T00:32:51.030+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:32:51.036+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-04-18T00:32:51.037+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:32:51.037+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]>
[2025-04-18T00:32:51.039+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:32:51.039+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-04-18T00:32:51.041+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:32:51.045+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-04-18T00:32:51.045+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [queued]>
[2025-04-18T00:32:51.045+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-04-18T00:32:51.056+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2025-04-18 00:20:00+00:00
[2025-04-18T00:32:51.061+0000] {standard_task_runner.py:57} INFO - Started process 216 to run task
[2025-04-18T00:32:51.064+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'parquet_to_csv_to_postgres_loader', 'load_csv_to_postgres', 'scheduled__2025-04-18T00:20:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/parquet_to_postgres_dbt.py', '--cfg-path', '/tmp/tmpd4mbq6vc']
[2025-04-18T00:32:51.067+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask load_csv_to_postgres
[2025-04-18T00:32:51.068+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0xffffb126daf0>]
[2025-04-18T00:32:51.141+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:32:51.144+0000] {task_command.py:416} INFO - Running <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [running]> on host 606609f4e4b0
[2025-04-18T00:32:51.145+0000] {settings.py:351} DEBUG - Disposing DB connection pool (PID 216)
[2025-04-18T00:32:51.145+0000] {settings.py:210} DEBUG - Setting up DB connection pool (PID 216)
[2025-04-18T00:32:51.146+0000] {settings.py:283} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-04-18T00:32:51.148+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [running]> from DB
[2025-04-18T00:32:51.202+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:32:51.203+0000] {taskinstance.py:925} DEBUG - Clearing XCom data
[2025-04-18T00:32:51.211+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-04-18T00:32:51.234+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-04-18T00:32:51.247+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parquet_to_csv_to_postgres_loader' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T00:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-18T00:20:00+00:00'
[2025-04-18T00:32:51.247+0000] {__init__.py:116} DEBUG - Preparing lineage inlets and outlets
[2025-04-18T00:32:51.247+0000] {__init__.py:157} DEBUG - inlets: [], outlets: []
[2025-04-18T00:32:51.274+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parquet_to_postgres_dbt.py", line 59, in load_csv_to_postgres
    """, (row['id'], row['csv_data']))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'id'
[2025-04-18T00:32:51.278+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres scheduled__2025-04-18T00:20:00+00:00 [running]> from DB
[2025-04-18T00:32:51.288+0000] {taskinstance.py:2430} DEBUG - Task Duration set to 0.250919
[2025-04-18T00:32:51.289+0000] {taskinstance.py:1458} DEBUG - Clearing next_method and next_kwargs.
[2025-04-18T00:32:51.290+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parquet_to_csv_to_postgres_loader, task_id=load_csv_to_postgres, execution_date=20250418T002000, start_date=20250418T003251, end_date=20250418T003251
[2025-04-18T00:32:51.306+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2025-04-18T00:32:51.306+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 72 for task load_csv_to_postgres ('id'; 216)
[2025-04-18T00:32:51.331+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-18T00:32:51.351+0000] {dagrun.py:734} DEBUG - number of tis tasks for <DagRun parquet_to_csv_to_postgres_loader @ 2025-04-18 00:20:00+00:00: scheduled__2025-04-18T00:20:00+00:00, state:running, queued_at: 2025-04-18 00:27:45.290166+00:00. externally triggered: False>: 0 task(s)
[2025-04-18T00:32:51.352+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
